### ISSUE TITLE
Some designous plans

### ISSUE THREAD

**Issue by sagikazarmark** [toin0u/concise#1]
- [x] Use [egeloen/ivory-http-adapter](https://github.com/egeloen/ivory-http-adapter) as http adapter implementation. (Since the need for always installing symfony event dispatcher has gone, it is the most decent one I found) ~~See branch feature/ivory-adapter~~ **Merged**
- [x] Add more providers (~~Chain~~, ~~Cache~~, Bitly, Tinycc, Owly)
- [x] ~~Error handling (handle faulty responses)~~ **Moved to #4**
- [x] Close on to the package structure of The PHP League skeleton (as we probably want to propose this package) (README structure, changelog, contributing guide) ~~See branch feature/readme~~ **Merged**
- [x] Drop PHP 5.3 support (The most recent HTTP libraries already did)

**Comment by sagikazarmark** [comment]
@toin0u anything to add?

**Comment by toin0u** [comment]
I think when all those todo will be implemented - the package will be very complete :)
[edited] let's drop the visitor pattern for the moment..

**Comment by sagikazarmark** [comment]
Scrutinizer is derping: composer build is old, ivory adapter uses some feature from a new version of composer. Till then scrutinizer builds will fail. :(

**Comment by toin0u** [comment]
mmm Is it because of the caret operator ? https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators

**Comment by sagikazarmark** [comment]
It is. :(

Here is the relevant issue: scrutinizer-ci/scrutinizer#290

**Comment by toin0u** [comment]
Ok thank you :)

**Comment by sagikazarmark** [comment]
It seems to be fixed now

**Comment by sagikazarmark** [comment]
Thinking about dropping Owly from the list. That bastard only allows login by twitter and requests permission to nearly everything.
