### ISSUE TITLE
Concise CLI

### ISSUE THREAD

**Issue by sagikazarmark** [toin0u/concise#3]
Planning to create a CLI application to shorten urls from cli. It could use phpdotenv to store credentials  and default provider in file.

Should it be go into a separate repository? (Also, providing a phar is a must)

**Comment by toin0u** [comment]
That's a great idea :) I think it's a good idea to create an other repo as well :+1:

**Comment by sagikazarmark** [comment]
Will you create it? Eg. concise-cli?

**Comment by toin0u** [comment]
Done !
